const NEW_MESSAGE = 'NEW_MESSAGE';
const NEW_RESPONSE = 'NEW_RESPONSE';
const MESSAGE_RATE = 'MESSAGE_RATE';
const RESPONSE_RATE = 'RESPONSE_RATE';

module.exports = {
	NEW_MESSAGE,
	NEW_RESPONSE,
	MESSAGE_RATE,
	RESPONSE_RATE,
};
